SET MODE=MySQL;
drop table if exists base_user;
CREATE TABLE `base_user` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`LOGIN_NAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '登录名',
	`LOGIN_PASSWORD` VARCHAR(100) NULL DEFAULT NULL COMMENT '登录密码',
	`PASSWORD_SALT` VARCHAR(50) NULL DEFAULT NULL COMMENT '密码盐',
	`ORGANIZATION_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '组织ID',
	`REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '姓名',
	`PHONE_NUMBER` VARCHAR(20) NULL DEFAULT NULL COMMENT '手机号码',
	`TELEPHONE_NUMBER` VARCHAR(20) NULL DEFAULT NULL COMMENT '电话号码',
	`EMAIL_ADDRESS` VARCHAR(30) NULL DEFAULT NULL COMMENT '电子邮箱',
	`CONTACT_ADDRESS` VARCHAR(100) NULL DEFAULT NULL COMMENT '联系地址',
	`REMARK` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
	`EXPIRATION_DATE` BIGINT(20) NULL DEFAULT NULL COMMENT '过期时间',
	`CREATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '创建时间',
	`UPDATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '更新时间',
	`CREATE_USER_ACCOUNT` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建用户登录名',
	`CREATE_USER_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建用户姓名',
	`UPDATE_USER_ACCOUNT` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新用户登录名',
	`UPDATE_USER_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新用户姓名',
	`ENABLE_FLAG` TINYINT NULL DEFAULT 0 COMMENT '停启用状态',
	`DEL_FLAG` TINYINT NULL DEFAULT 0 COMMENT '逻辑删除标记',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `IDX_USER_LOGIN_NAME` (`LOGIN_NAME`)
);

insert into BASE_USER (LOGIN_NAME,LOGIN_PASSWORD,ORGANIZATION_ID,REALNAME,PHONE_NUMBER,TELEPHONE_NUMBER,EMAIL_ADDRESS,CONTACT_ADDRESS,REMARK,EXPIRATION_DATE,CREATE_TIME,UPDATE_TIME,CREATE_USER_ACCOUNT,CREATE_USER_REALNAME,UPDATE_USER_ACCOUNT,UPDATE_USER_REALNAME,ENABLE_FLAG,DEL_FLAG)
VALUES ('admin', '$2a$10$S.AZBpSZ3kaF50XA2SiM1OSzrsuR1HLT4foXR.6Ffi/mlynHzBcFO', 1, 'admin', 15888888888, null, 'admin@evm.com', null, null, null, 1574399670882, null, null, null, null, null, 0, 0);

CREATE TABLE `base_organization` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`ORG_CODE` VARCHAR(50) NULL DEFAULT NULL COMMENT '机构代码',
	`ORG_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '机构名称',
	`PARENT_ORG_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '上级机构ID',
	`CONTACT_NAME` VARCHAR(20) NULL DEFAULT NULL COMMENT '联系人姓名',
	`FAX_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '传真',
	`TELEPHONE_NUMBER` VARCHAR(20) NULL DEFAULT NULL COMMENT '电话号码',
	`EMAIL_ADDRESS` VARCHAR(30) NULL DEFAULT NULL COMMENT '电子邮箱',
	`PROVINCE_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '所在省代码',
	`CITY_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '所在市代码',
	`COUNTY_NAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '所在县区代码',
	`CONTACT_ADDRESS` VARCHAR(100) NULL DEFAULT NULL COMMENT '联系地址',
	`OFFICIAL_SITE` VARCHAR(100) NULL DEFAULT NULL COMMENT '官方网站',
	`ORG_TYPE` BIGINT(20) NULL DEFAULT NULL COMMENT '机构类型。关联数据字典代码ORGANIZATION_TYPE下属明细项ID',
	`REMARK` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
	`CREATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '创建时间',
	`UPDATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '更新时间',
	`CREATE_USER_ACCOUNT` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建用户登录名',
	`CREATE_USER_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建用户姓名',
	`UPDATE_USER_ACCOUNT` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新用户登录名',
	`UPDATE_USER_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新用户姓名',
	`ENABLE_FLAG` TINYINT(4) NULL DEFAULT NULL COMMENT '停启用状态',
	`DEL_FLAG` TINYINT(4) NULL DEFAULT '0' COMMENT '逻辑删除标记',
	`PATH` VARCHAR(500) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `IDX_ORG_PATH` (`ID`)
);

INSERT INTO `base_organization` (`ID`, `ORG_CODE`, `ORG_NAME`, `PARENT_ORG_ID`, `CONTACT_NAME`, `FAX_NO`, `TELEPHONE_NUMBER`, `EMAIL_ADDRESS`, `PROVINCE_NAME`, `CITY_NAME`, `COUNTY_NAME`, `CONTACT_ADDRESS`, `OFFICIAL_SITE`, `ORG_TYPE`, `REMARK`, `CREATE_TIME`, `UPDATE_TIME`, `CREATE_USER_ACCOUNT`, `CREATE_USER_REALNAME`, `UPDATE_USER_ACCOUNT`, `UPDATE_USER_REALNAME`, `ENABLE_FLAG`, `DEL_FLAG`, `PATH`)
VALUES (1, NULL, '天泽信息', -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1568104322112, NULL, NULL, NULL, NULL, NULL, 0, 0, '1/');

CREATE TABLE `base_role` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`ROLE_CODE` VARCHAR(50) NULL DEFAULT NULL COMMENT '角色代码',
	`ROLE_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '角色名称',
	`REMARK` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
	`EXPIRATION_DATE` BIGINT(20) NULL DEFAULT NULL COMMENT '过期时间',
	`CREATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '创建时间',
	`UPDATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '更新时间',
	`CREATE_USER_ACCOUNT` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建用户登录名',
	`CREATE_USER_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建用户姓名',
	`UPDATE_USER_ACCOUNT` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新用户登录名',
	`UPDATE_USER_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新用户姓名',
	`ENABLE_FLAG` TINYINT(4) NULL DEFAULT '0' COMMENT '停启用状态',
	`DEL_FLAG` TINYINT(4) NULL DEFAULT '0' COMMENT '逻辑删除标记',
	`ORGANIZATION_ID` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
);

INSERT INTO `base_role` (`ID`, `ROLE_CODE`, `ROLE_NAME`, `REMARK`, `EXPIRATION_DATE`, `CREATE_TIME`, `UPDATE_TIME`, `CREATE_USER_ACCOUNT`, `CREATE_USER_REALNAME`, `UPDATE_USER_ACCOUNT`, `UPDATE_USER_REALNAME`, `ENABLE_FLAG`, `DEL_FLAG`, `ORGANIZATION_ID`)
VALUES (1, NULL, '管理员', NULL, NULL, 1568106566413, NULL, 'admin', NULL, NULL, NULL, 0, 0, 1);

CREATE TABLE `base_authorize` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`AUTHORIZE_OBJECT_TYPE` TINYINT(4) NULL DEFAULT '0' COMMENT '授权对象类型。(预留多种赋权方式，默认0，对角色赋权)',
	`AUTHORIZE_OBJECT_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '授权对象ID',
	`PERMISSION_TYPE` TINYINT(4) NULL DEFAULT NULL COMMENT '权限项类型。0.平台；1.系统；2.功能；3.操作',
	`PERMISSION_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '权限项ID',
	`AUTHORIZE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '授权时间',
	`AUTHORIZE_ACCOUNT` DOUBLE NULL DEFAULT NULL COMMENT '授权账号',
	`AUTHORIZE_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '授权用户姓名',
	`CHECK_STATUS` TINYINT(4) NULL DEFAULT NULL COMMENT '选中状态 0半选 1全选',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `base_role_user` (
	`USER_ID` BIGINT(20) NOT NULL COMMENT '用户ID',
	`ROLE_ID` BIGINT(20) NOT NULL COMMENT '角色ID',
	`CREATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '创建时间',
	PRIMARY KEY (`USER_ID`, `ROLE_ID`)
);
CREATE TABLE `base_sys_function` (
	`ID` BIGINT(20) NOT NULL COMMENT '主键ID',
	`FUNCTION_CODE` VARCHAR(50) NULL DEFAULT NULL COMMENT '功能代码',
	`FUNCTION_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '功能名称',
	`PARENT_FUNCTION_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '上级功能ID',
	`ORGANIZATION_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '所属机构ID',
	`LAYER_LEVEL` TINYINT(4) NULL DEFAULT NULL COMMENT '层级(平台级多系统时使用。0.平台；1.系统；2.功能)',
	`FUNCTION_TYPE` TINYINT(4) NULL DEFAULT NULL COMMENT '功能类型(0.功能组；1.功能;2.操作)',
	`NAVI_URL` VARCHAR(200) NULL DEFAULT NULL COMMENT '导航链接',
	`ICON` VARCHAR(50) NULL DEFAULT NULL COMMENT '图标',
	`IS_NEW_PAGE` TINYINT(4) NULL DEFAULT NULL COMMENT '是否打开新页面',
	`SORT_CODE` INT(11) NULL DEFAULT '1' COMMENT '排序码',
	`REMARK` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
	`CREATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '创建时间',
	`UPDATE_TIME` BIGINT(20) NULL DEFAULT NULL COMMENT '更新时间',
	`CREATE_USER_ACCOUNT` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建用户登录名',
	`CREATE_USER_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '创建用户姓名',
	`UPDATE_USER_ACCOUNT` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新用户登录名',
	`UPDATE_USER_REALNAME` VARCHAR(25) NULL DEFAULT NULL COMMENT '更新用户姓名',
	`ENABLE_FLAG` TINYINT(4) NULL DEFAULT '0' COMMENT '停启用状态',
	`DEL_FLAG` TINYINT(4) NULL DEFAULT '0' COMMENT '逻辑删除标记'
);

