avatar:

server:
  compression:
    enabled: true
    min-response-size: 2048

logging:
  level:
    cn.com.tiza: DEBUG

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

swagger:
  enabled: true
  base-package: cn.com.tiza.web
  title: tiza-feisi
  version: 2.0.0-SNAPSHOT

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB