server:
  port: 8082

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
      - id: SystemService
        uri: lb://feisi-system
        predicates:
          - Path=/app/system/**
        filters:
          - StripPrefix=2
          - PrefixPath=/app
      - id: VehicleService
        uri: lb://feisi-vehicle
        predicates:
          - Path=/app/vehicle/**
        filters:
          - StripPrefix=2
          - PrefixPath=/app
      - id: MonitorService
        uri: lb://feisi-monitor
        predicates:
          - Path=/app/monitor/**
        filters:
          - StripPrefix=2
          - PrefixPath=/app

gate:
  ignore:
    startWith: /auth/login,/auth/logout

auth:
  jwt:
    # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
    base64-secret: NjliMjMwMzg3YzM4NmE1MTM0OWJjOWE3NTQxNjk1MWViOTlmMDYzMTc5YTA2Mjg1NjMwNzUyNzM2OWFlOGQ2NWY0M2NiYmM0MThkZDM1ODRkNTgzOGFlM2Y5YWU4ZWIwYWQ4ZDY2ODg1ZTIxNGQxNjUwNjljZDgyMWQyMzRiNWQ=
    # Token is valid 24 hours
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000

