server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

# development environment
---
spring:
  profiles: dev

eureka:
  instance:
    prefer-ip-address: true
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: test

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_MASTER_HOST}:${REGISTRY_PORT}/eureka/,http://${REGISTRY_BACKUP_HOST}:${REGISTRY_PORT}/eureka/

